spring:
  application:
    name: Produtos Api  # Nome da aplicação
  datasource:
    url: jdbc:h2:mem:produtos # URL do banco de dados
    username: admin  # Usuário do banco de dados
    password: admin  # Senha do banco de dados
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect # Dialeto do banco de dados
  h2:
    console:
      enabled: true # Habilita o console do H2
      path: /h2-console # Caminho do console do H2
  hibernate:
      ddl-auto: create-drop # Estratégia de criação do banco de dados
